name = "sports-api"
main = "src/index.ts"
compatibility_date = "2024-11-30"

# [vars]
# MY_VAR = "my-variable"


[[d1_databases]]
binding = "DB"
database_name = "sports-db"
database_id = "your-database-id"