name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches:
      - production
    paths:
      - 'apps/admin/**'
  pull_request:
    branches:
      - production
    paths:
      - 'apps/admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Admin Website
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build --filter @sports/admin
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/admin'
          command: pages deploy dist
