name: Deploy API to Cloudflare Workers

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build --filter @sports/api
        
      - name: Create wrangler.toml
        run: |
          cat > apps/api/wrangler.toml << EOF
          name = "sports-api"
          main = "src/index.ts"
          compatibility_date = "2024-11-30"

          [vars]
          JWT_SECRET = "${{ secrets.JWT_SECRET }}"
          IMGBB_API_KEY = "${{ secrets.IMGBB_API_KEY }}"

          [[d1_databases]]
          binding = "DB"
          database_name = "gptc-pmna-sports-db"
          database_id = "${{ secrets.DATABASE_ID }}"
          migrations_dir = "drizzle"

          [observability]
          enabled = true
          head_sampling_rate = 1 # optional. default = 1.
          EOF
        
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/api'
          command: deploy
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
